#include <stdio.h>

#include <program.h>
#include <str.h>
#include <vars.h>

void main()
{
	qkbk_init("test1.asm");
	qkbk_write_comment("Generated by the backend.");
	qkbk_write_comment("This is a test file.");
	
	qkbk_print_str("Hello!");
	qkbk_print_str("Welcome to Quik!");
	qkbk_print_nl();
	
	qkbk_new_ivar("x", 22);
	qkbk_print_ivar("x");
	
	qkbk_print_iconst(15);
	
	qkbk_close();
}
